import type { Metadata } from "next";
import { logoCap } from "../../multitenant-images"
import "@styles/globals.css";
import '@styles/material-icons.css';
import links  from "../../fontlinks";
export const metadata: Metadata = {
  title: "Simple Site Generator",
  description: "Generated by Simple Site Generator",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://fonts.googleapis.com" />
        <link rel="stylesheet" href="https://fonts.gstatic.com" />
        <link rel="icon" href={logoCap} />
        { 
          links.map((value: any, i: number) => {
            return <link rel="stylesheet"
              key={i}
              href={value}
            
            />
          })
        }
      </head>
      <body
        className="bg-surface-0 font-sans"
      >
        {children}
      </body>
    </html>
  );
}
