import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import { favicon } from "../../multitenant-images"
import links  from "../../fontlinks"
import Script from "next/script"

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
  variable: "--geist-sans",
});

const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>

        <Script strategy="afterInteractive" src="https://fonts.googleapis.com" />
        <Script strategy="afterInteractive" src="https://fonts.gstatic.com" />
        <link rel="icon" href={favicon} />
        { 
          links.map((value: any, i: number) => {
            return <Script
              key={i}
              src={value}
              strategy="afterInteractive"
            />
          })
        }
      </head>
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
